name: Mix Tests

on: push

jobs:
  container-job:
    name: Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        elixir:
        - 1.6.x
        - 1.7.x
        - 1.8.x
        - 1.9.x
        - 1.10.x
        - 1.11.x
        - 1.12.x
        include:
        - elixir: 1.6.x
          otp: 20.x
        - elixir: 1.7.x
          otp: 22.x
        - elixir: 1.8.x
          otp: 22.x
        - elixir: 1.9.x
          otp: 22.x
        - elixir: 1.10.x
          otp: 22.x
        - elixir: 1.11.x
          otp: 23.x
        - elixir: 1.12.x
          otp: 24.x

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Mix Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-

    - name: Install Rebar and Hex
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        MIX_ENV: test
      run: |
        mix local.rebar --force
        mix local.hex --force

    - name: Install Dependencies
      env:
        MIX_ENV: test
      run: |
        mix deps.get

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Check compile warnings
      run: mix compile --warnings-as-errors --force

    - name: Dialyzer Cache
      uses: actions/cache@v2
      id: cache-dialyzer
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-dialyzer-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-dialyzer-

    - name: Dialyzer
      run: |
        mkdir -p priv/plts
        mix dialyzer

    - name: Run Tests
      run: mix test
